inventory_project/inventory_project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'inventory.views.home'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'inventory.views.logout_view'),
    url(r'^receipt/$', 'inventory.views.receipt'),
    url(r'^add-location/$', 'inventory.views.add_location'),
    url(r'^add-network/$', 'inventory.views.add_network'),
    url(r'^ajax-add-location/$', 'inventory.views.ajax_add_location'),
    url(r'^reports/inventory/$', 'inventory.views.reports_inventory'),
    url(r'^reports/inventory-storage/$', 'inventory.views.reports_inventory_storage'),
    url(r'^reports/movements/$', 'inventory.views.reports_movements'),
    url(r'^reports/statistics/$', 'inventory.views.reports_statistics'),
    url(r'^requests/add/receipt$', 'inventory.views.requests_add_receipt'),
    url(r'^requests/check-availability/1/$', 'inventory.views.ajax_check_availability_receipt'),
    url(r'^requests/add/expense$', 'inventory.views.requests_add_expense'),
    url(r'^requests/check-availability/2/$', 'inventory.views.ajax_check_availability_expense'),
    url(r'^requests/create-or-update-packet/$', 'inventory.views.ajax_create_or_update_packet'),
    url(r'^requests/list/$', 'inventory.views.requests_list'),
    url(r'^requests/list-processed/$', 'inventory.views.requests_list_processed'),
    url(r'^requests/list-mine/$', 'inventory.views.requests_list_mine'),
    url(r'^requests/view/(?P<id>\d+)?$', 'inventory.views.requests_view'),
    url(r'^requests/process/(?P<id>\d+)?$', 'inventory.views.requests_process'),
    url(r'^stocktaking/list/$', 'inventory.views.stocktaking_list'),
    url(r'^stocktaking/process/(?P<box_id>\d+)?$', 'inventory.views.stocktaking_process'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

inventory_project/inventory/models.py
# -*- coding: utf8 -*-
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField('название', unique=True, max_length=255)
    is_permanent = models.BooleanField('является постоянным', default=False)
    minimal_quantity_in_storage = models.IntegerField(
        'минимальное необходимое количество на складе', blank=True, default=0)
    deleted = models.BooleanField('удален')

    class Meta:
        verbose_name = 'наименование'
        verbose_name_plural = 'наименования'

    def __unicode__(self):
        return self.name


class BoxType(models.Model):
    name = models.CharField('название', unique=True, max_length=255)

    class Meta:
        verbose_name = 'тип коробки'
        verbose_name_plural = 'типы коробок'

    def __unicode__(self):
        return self.name


class Network(models.Model):
    name = models.CharField('название', unique=True, max_length=255)

    class Meta:
        verbose_name = 'сеть'
        verbose_name_plural = 'сети'

    def __unicode__(self):
        return self.name


class Box(models.Model):
    name = models.CharField('название', unique=True, max_length=255)
    box_type = models.ForeignKey(BoxType, verbose_name='тип коробки')
    network = models.ForeignKey(Network, default=1, verbose_name='сеть')
    deleted = models.BooleanField('удален')

    class Meta:
        verbose_name = 'коробка'
        verbose_name_plural = 'коробки'

    def __unicode__(self):
        return self.name


class InventoryItem(models.Model):
    box = models.ForeignKey(Box, verbose_name='коробка')
    item = models.ForeignKey(Item, verbose_name='наименование')
    quantity = models.IntegerField('количество')

    class Meta:
        verbose_name = 'наличие'
        verbose_name_plural = 'наличие'

    def __unicode__(self):
        return '"%s" - "%s" (%d)' % (
            self.box.name, self.item.name, self.quantity)


class Movement(models.Model):
    box_from = models.ForeignKey(Box, related_name='box_from',
                                 verbose_name='коробка от')
    box_to = models.ForeignKey(Box, related_name='box_to',
                               verbose_name='коробка к')
    item = models.ForeignKey(Item, verbose_name='наименование')
    quantity = models.IntegerField('количество')
    date = models.DateTimeField('дата', auto_now_add=True)
    comment = models.CharField('комментарий', max_length=255, null=True,
                               blank=True)

    class Meta:
        verbose_name = 'перемещение'
        verbose_name_plural = 'перемещения'

    def __unicode__(self):
        return '"%s" -> "%s" - "%s" (%d)' % (self.box_from.name,
                                             self.box_to.name,
                                             self.item.name,
                                             self.quantity)


class Packet(models.Model):
    class Meta:
        verbose_name = 'пакет'
        verbose_name_plural = 'пакеты'


class PacketItem(models.Model):
    packet = models.ForeignKey(Packet, verbose_name='пакет')
    box = models.ForeignKey(Box, verbose_name='коробка')
    item = models.ForeignKey(Item, verbose_name='наименование')
    quantity = models.IntegerField('количество')
    comment = models.CharField('комментарий', max_length=255, null=True,
                               blank=True)

    class Meta:
        verbose_name = 'содержимое пакета'
        verbose_name_plural = 'содержимое пакета'

    def __unicode__(self):
        return '%s" (%d)' % (self.item.name, self.quantity)


class RequestType(models.Model):
    name = models.CharField('название', unique=True, max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'название'
        verbose_name_plural = 'названия'


class Request(models.Model):
    request_type = models.ForeignKey(RequestType, verbose_name='тип заявки')
    user = models.ForeignKey(User, verbose_name='пользователь')
    person = models.ForeignKey(Box, verbose_name='лицо')
    packet = models.ForeignKey(Packet, verbose_name='пакет', unique=True)
    date = models.DateTimeField('дата/время', auto_now_add=True)
    processed = models.BooleanField('обработано')

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'

    def __unicode__(self):
        return '"%s", "%s"' % (self.user.username, self.person.name)

inventory_project/inventory/forms.py
# -*- coding: utf8 -*-
from django import forms
from datetime import timedelta, date, datetime
from django.conf import settings
from inventory.models import Item, Box, Request, InventoryItem, Network
from django.contrib.auth.models import User


def load_dates_initial():
    return date.today() - timedelta(days=30), date.today()


def load_dates_initial_stats():
    return datetime.strptime(
        settings.START_DATE, settings.FORMAT_DATE), date.today()
default_value = [('', '-' * 9)]


def convert_date_to_datetime(date):
    'convert date to datetime to show last day results'
    return datetime(date.year, date.month, date.day, 23, 59, 59)


class Choices:
    def __init__(self, hide_deleted=True):
        self.hide_deleted = hide_deleted
        self.items = self.create_items_list()
        self.persons = self.create_box_list(5)
        self.storage = self.create_box_list(1)
        self.locations = self.create_box_list(6)
        self.correction = self.create_box_list(4)
        self.expense = self.create_box_list(2)
        self.receipt = self.create_box_list(3)
        self.storage_with_locations = self.storage + self.locations
        self.expense_and_storage_with_locations = (self.expense + self.storage +
                                                   self.locations)  # for views
        self.basic_set = (self.storage + self.persons + self.locations +
                          self.correction)
        self.boxes_from = self.receipt + self.basic_set
        self.boxes_to = self.expense + self.basic_set
        self.boxes = self.receipt + self.expense + self.basic_set
        self.persons_with_no_default_value = default_value + self.persons

    def create_list(self, objects):
        choices = []
        for object in objects:
            choices.append((object.pk, object.name))
        return choices

    def create_items_list(self):
        items = Item.objects.all()
        if self.hide_deleted:
            items = items.exclude(deleted=True)
        items = items.order_by('name')
        return self.create_list(items)

    def create_box_list(self, id):
        boxes = Box.objects.filter(box_type=id)
        if self.hide_deleted:
            boxes = boxes.exclude(deleted=True)
        boxes = boxes.order_by('name')
        return self.create_list(boxes)

    def output(self, list):
        return [(0, '')] + list

    def output_items(self):
        return self.output(self.items)

    def output_persons(self):
        return self.output(self.persons)

    def output_storage_with_locations(self):
        return self.output(self.storage_with_locations)

    def output_boxes_from(self):
        return self.output(self.boxes_from)

    def output_boxes_to(self):
        return self.output(self.boxes_to)

    def output_boxes(self):
        return self.output(self.boxes)


class RequestAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RequestAddForm, self).__init__(*args, **kwargs)
        self.fields['person'].choices = Choices().persons_with_no_default_value

    person = forms.ChoiceField(label='Лицо')

    class Meta:
        model = Request
        exclude = ('user', 'date', 'processed')
        widgets = {
            'request_type': forms.HiddenInput(),
            'packet': forms.HiddenInput(),
        }

    def clean_person(self):
        return Box.objects.get(pk=self.cleaned_data['person'])


class ReceiptForm(forms.ModelForm):
    item = forms.CharField(label='Наименование',
                           widget=forms.TextInput(
                               attrs={'required': '', 'autofocus': ''}))
    comment = forms.CharField(label='Комментарий', required=False)

    def clean_item(self):
        # Add a new item if it's not in the database yet.
        item, _ = Item.objects.get_or_create(
            name=self.cleaned_data['item'])
        return item

    def clean_quantity(self):
        if self.cleaned_data['quantity'] < 1:
            raise forms.ValidationError(
                'Введите количество большее или равное 1')
        return self.cleaned_data['quantity']

    class Meta:
        model = InventoryItem
        exclude = ('box',)
        widgets = {
            'quantity': forms.TextInput(attrs={'required': '',
                                               'pattern': '\d+',
                                               'title': 'число'}),
        }


class LocationForm(forms.ModelForm):
    name = forms.CharField(label='Адрес', widget=forms.TextInput(
        attrs={'required': '', 'autofocus': ''}))

    def clean_name(self):
        return self.cleaned_data['name'].strip()

    class Meta:
        model = Box
        exclude = ('box_type', 'deleted')


class NetworkForm(forms.ModelForm):
    name = forms.CharField(label="Название", widget=forms.TextInput(
        attrs={'required': '', 'autofocus': ''}))

    def clean_name(self):
        return self.cleaned_data['name'].strip()

    class Meta:
        model = Network


class InventoryReportForm(forms.Form):
    IS_PERMANENT_NOT_SELECTED = 0
    IS_PERMANENT_YES = 1
    IS_PERMANENT_NO = 2

    def __init__(self, *args, **kwargs):
            super(InventoryReportForm, self).__init__(*args, **kwargs)
            choices = Choices()
            self.fields['item'].choices = choices.output_items()
            self.fields['item_is_permanent'].choices = (
                (self.IS_PERMANENT_NOT_SELECTED, ''),
                (self.IS_PERMANENT_NO, 'Нет'),
                (self.IS_PERMANENT_YES, 'Да'))
            self.fields['person'].choices = choices.output_persons()
            self.fields['location'].choices = choices.output_storage_with_locations()
            self.fields['network'].choices = [(0, '')] + list(Network.objects.all().values_list())

    item = forms.ChoiceField(label='Наименование', required=False)
    item_is_permanent = forms.ChoiceField(label='Наименование является постоянным', required=False)
    person = forms.ChoiceField(label='Лицо', required=False)
    location = forms.ChoiceField(label='Узел', required=False)
    network = forms.ChoiceField(label='Сеть', required=False)

    def clean_item(self):
        if not int(self.cleaned_data['item']):
            return
        return Item.objects.get(pk=self.cleaned_data['item'])

    def clean_item_is_permanent(self):
        value = int(self.cleaned_data['item_is_permanent'])
        if value == self.IS_PERMANENT_YES:
            return True
        if value == self.IS_PERMANENT_NO:
            return False

    def clean_person(self):
        if not int(self.cleaned_data['person']):
            return
        return Box.objects.get(pk=self.cleaned_data['person'])

    def clean_location(self):
        if not int(self.cleaned_data['location']):
            return
        return Box.objects.get(pk=self.cleaned_data['location'])

    def clean_network(self):
        if not int(self.cleaned_data['network']):
            return
        return Network.objects.get(pk=self.cleaned_data['network'])


def create_form_date_fields(dates):
    def create_form_date_field(label, initial_date):
        widget_attrs = {'required': '', 'pattern': '^\d{2}\.\d{2}\.\d{4}$'}
        return forms.DateField(label=label,
                               initial=initial_date,
                               widget=forms.DateInput(
                                   attrs=widget_attrs,
                                   format=settings.FORMAT_DATE),
                               input_formats=(settings.FORMAT_DATE,))
    date_from = create_form_date_field('От', dates[0])
    date_to = create_form_date_field('До', dates[1])
    return (date_from, date_to)


class StatsReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
            super(StatsReportForm, self).__init__(*args, **kwargs)
            users = User.objects.all()
            users = [(user.pk, user.get_full_name()) for user in users]
            self.fields['user'].choices = default_value + users

    user = forms.ChoiceField(label='Пользователь', required=False)
    period = forms.ChoiceField(label='Период', required=True, choices=[
        (7, 'неделя'),
        (30, 'месяц'),
        (180, 'полгода')]
    )
    date_from, date_to = create_form_date_fields(load_dates_initial_stats())

    def clean_user(self):
        if not self.cleaned_data['user']:
            return
        return User.objects.get(pk=self.cleaned_data['user'])

    def clean_period(self):
        return int(self.cleaned_data['period'])


class MovementsReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(MovementsReportForm, self).__init__(*args, **kwargs)
        choices = Choices(False)
        self.fields['box'].choices = choices.output_boxes()
        self.fields['box_from'].choices = choices.output_boxes_from()
        self.fields['box_to'].choices = choices.output_boxes_to()
        self.fields['item'].choices = choices.output_items()

    box = forms.ChoiceField(label='Коробка', required=False)
    box_from = forms.ChoiceField(label='Откуда', required=False)
    box_to = forms.ChoiceField(label='Куда', required=False)
    item = forms.ChoiceField(label='Наименование', required=False)
    date_from, date_to = create_form_date_fields(load_dates_initial())
    comment_sort = forms.BooleanField(label='Сортировка по комментарию',
                                      required=False)

    def clean_item(self):
        if not int(self.cleaned_data['item']):
            return
        return Item.objects.get(pk=self.cleaned_data['item'])

    def clean_box_from(self):
        if not int(self.cleaned_data['box_from']):
            return
        return Box.objects.get(pk=self.cleaned_data['box_from'])

    def clean_box_to(self):
        if not int(self.cleaned_data['box_to']):
            return
        return Box.objects.get(pk=self.cleaned_data['box_to'])

    def clean_box(self):
        if not int(self.cleaned_data['box']):
            return

inventory_project/templates/reports/inventory-storage.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-center">Отчёт о наличие необходимого оборудования на Складе</h1>
{% if items %}
<div id="to-print">
  <table class="table">
    <thead>
      <tr>
        <th>Наименование</th>
        <th>В наличие</th>
        <th>Необходимо</th>
      </tr>
    </thead>
    <tbody>
    {% for item in items %}
      <tr>
          <td>{{ item.0 }}</td>
          <td>{{ item.1 }}</td>
          <td>{{ item.2 }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

{% endblock %}

inventory_project/templates/reports/inventory.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

<script>
  function reset_form() {
    $('#id_item').val('0');
    $('#id_location').val('0');
    $('#id_person').val('0');
    $('#id_network').val('0');
  }
</script>
<h1 class="text-center">Отчёт о наличие</h1>
<form enctype="multipart/form-data" action="" method="POST" id="receipt" class="form-horizontal">
  {% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="control-group">
    <div class="controls">
        <input type="submit" value="Сформировать" class="btn btn-primary">
        <input type="button" value="Сбросить" onclick="reset_form()" class="btn">
        <input type="button" value="Печать" onclick="window.print()" class="btn">
    </div>
  </div>
</form>

{% if items %}
<div id="to-print">
  <table class="table">
    <thead>
      <tr>
        <th>Коробка</th>
        <th>Наименование</th>
        <th>Количество</th>
      </tr>
    </thead>
    <tbody>
    {% for item in items %}
      <tr>
          <td>{{ item.box }}</td>
          <td>{{ item.item }}</td>
          <td>{{ item.quantity }}</td>
      </tr>
    {% endfor %}
    {% for box in empty_boxes %}
      <tr>
          <td>{{ box }}</td>
          <td></td>
          <td></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}


{% endblock %}

inventory_project/templates/reports/movements.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

<script src="/static/js/date.js"></script>
<script src="/static/libs/datepicker_ru.js"></script>
<script>
  function reset_form() {
    $('#id_item').val('0');
    $('#id_box_from').val('0');
    $('#id_box_to').val('0');
    $('#id_box').val('0');
    $('#id_date_from').val('{{ date_initial.0 }}');
    $('#id_date_to').val('{{ date_initial.1 }}');
  }
</script>
<h1 class="text-center">Отчёт о перемещениях</h1>
<form enctype="multipart/form-data" action="" method="POST" id="receipt" class="form-horizontal">
  {% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="control-group">
    <div class="controls">
        <input type="submit" value="Сформировать" class="btn btn-primary">
        <input type="button" value="Сбросить" onclick="reset_form()" class="btn">
        <input type="button" value="Печать" onclick="window.print()" class="btn">
    </div>
  </div>
</form>

{% if movements %}
<div id="to-print">
  <table class="table">
    <thead>
      <tr>
        <th>Откуда</th>
        <th>Куда</th>
        <th>Наименование</th>
        <th>Количество</th>
        <th>Дата</th>
        <th>Комментарий</th>
      </tr>
    </thead>
    <tbody>
  {% for movement in movements %}
      <tr>
          <td>{{ movement.box_from }}</td>
          <td>{{ movement.box_to }}</td>
          <td>{{ movement.item }}</td>
          <td>{{ movement.quantity }}</td>
          <td>{{ movement.date }}</td>
          <td>{% if movement.comment %} {{ movement.comment }} {% endif %}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

{% endblock %}

inventory_project/templates/reports/statistics.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

<script src="/static/js/date.js"></script>
<script src="/static/libs/datepicker_ru.js"></script>
<script>
  function reset_form() {
    $('#id_user').val('');
    $('#id_period').val('7');
    $('#id_date_from').val('{{ dates_initial.0 }}');
    $('#id_date_to').val('{{ dates_initial.1 }}');
  }
</script>
<h1 class="text-center">Отчёт о статистике расхода материалов</h1>
<form enctype="multipart/form-data" action="" method="POST" id="receipt" class="form-horizontal">
  {% csrf_token %}
  {{ form|as_bootstrap }}
  <div class="control-group">
    <div class="controls">
        <input type="submit" value="Сформировать" class="btn btn-primary">
        <input type="button" value="Сбросить" onclick="reset_form()" class="btn">
        <input type="button" value="Печать" onclick="window.print()" class="btn">
    </div>
  </div>
</form>

{% if items %}
<div id="to-print">
  <table class="table">
    <thead>
      <tr>
        <th>Наименование</th>
        <th>Израсходовано</th>
        <th>Расход в период</th>
      </tr>
    </thead>
    <tbody>
    {% for item in items %}
      <tr>
          <td>{{ item.0 }}</td>
          <td>{{ item.1 }}</td>
          <td>{{ item.2 }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}


{% endblock %}